# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-05 16:13
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Admet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_name', models.CharField(max_length=20, verbose_name='\u4efb\u52a1\u540d\u79f0')),
                ('work_decs', models.CharField(default='', max_length=100, verbose_name='\u4efb\u52a1\u63cf\u8ff0')),
                ('mol_file', models.FileField(upload_to='media/%Y/%m/%d/', verbose_name='\u5c0f\u5206\u5b50\u6587\u4ef6')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u7528\u6237')),
            ],
            options={
                'verbose_name': 'ADMET\u9884\u6d4b',
                'verbose_name_plural': 'ADMET\u9884\u6d4b',
            },
        ),
        migrations.CreateModel(
            name='AutoDuck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_name', models.CharField(max_length=20, verbose_name='\u4efb\u52a1\u540d\u79f0')),
                ('work_decs', models.CharField(default='', max_length=100, verbose_name='\u4efb\u52a1\u63cf\u8ff0')),
                ('mol_db', models.CharField(choices=[(1, 'zinc'), (2, 'chembl')], max_length=10, verbose_name='\u6570\u636e\u5e93\u9009\u62e9')),
                ('size_x', models.FloatField(verbose_name='size_x')),
                ('size_y', models.FloatField(verbose_name='size_y')),
                ('size_z', models.FloatField(verbose_name='size_y')),
                ('center_x', models.FloatField(verbose_name='center_x')),
                ('center_y', models.FloatField(verbose_name='center_y')),
                ('center_z', models.FloatField(verbose_name='center_z')),
                ('pdb_file', models.FileField(upload_to='media/%Y/%m/%d/', verbose_name='pdb\u6587\u4ef6')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u7528\u6237')),
            ],
            options={
                'verbose_name': '\u5206\u5b50\u5bf9\u63a5',
                'verbose_name_plural': '\u5206\u5b50\u5bf9\u63a5',
            },
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='banner', verbose_name='\u8f6e\u64ad\u56fe\u7247')),
                ('index', models.IntegerField(verbose_name='\u8f6e\u64ad\u987a\u5e8f')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u9996\u9875\u8f6e\u64ad\u56fe',
                'verbose_name_plural': '\u9996\u9875\u8f6e\u64ad\u56fe',
            },
        ),
        migrations.CreateModel(
            name='Dynamic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_name', models.CharField(max_length=20, verbose_name='\u4efb\u52a1\u540d\u79f0')),
                ('work_decs', models.CharField(default='', max_length=100, verbose_name='\u4efb\u52a1\u63cf\u8ff0')),
                ('conf_info', models.CharField(choices=[(1, '\u901a\u7528\u8ba1\u7b97'), (2, '\u8ba1\u7b97\u7ed3\u5408\u80fd'), (3, '\u8ba1\u7b97\u6c22\u952e'), (4, '\u805a\u7c7b\u5206\u6790')], max_length=20, verbose_name='\u914d\u7f6e\u4fe1\u606f')),
                ('protein_file', models.FileField(upload_to='media/%Y/%m/%d/', verbose_name='\u86cb\u767d\u6587\u4ef6')),
                ('mol_file', models.FileField(upload_to='media/%Y/%m/%d/', verbose_name='\u5c0f\u5206\u5b50\u6587\u4ef6')),
                ('conf_project', models.CharField(choices=[(1, '\u6709\u6c34'), (2, '\u65e0\u6c34'), (3, '\u81ea\u8ba1\u7b97')], max_length=100, verbose_name='\u914d\u7f6e\u9879\u76ee')),
                ('s_file', models.FileField(default='', upload_to='media/%Y/%m/%d/', verbose_name='S\u4fe1\u606f\u6587\u4ef6')),
                ('lig_file', models.FileField(default='', upload_to='media/%Y/%m/%d/', verbose_name='lig\u6587\u4ef6')),
                ('frcmod_file', models.FileField(default='', upload_to='media/%Y/%m/%d/', verbose_name='frcmod\u6587\u4ef6')),
                ('res_num', models.IntegerField(default=0, verbose_name='\u6c28\u57fa\u9178\u6570\u76ee')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u7528\u6237')),
            ],
            options={
                'verbose_name': '\u52a8\u529b\u5b66\u6a21\u62df',
                'verbose_name_plural': '\u52a8\u529b\u5b66\u6a21\u62df',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='\u670d\u52a1\u540d\u79f0')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u670d\u52a1\u5185\u5bb9',
                'verbose_name_plural': '\u670d\u52a1\u5185\u5bb9',
            },
        ),
        migrations.CreateModel(
            name='ReverseVirtualScreen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_name', models.CharField(max_length=20, verbose_name='\u4efb\u52a1\u540d\u79f0')),
                ('work_decs', models.CharField(default='', max_length=100, verbose_name='\u4efb\u52a1\u63cf\u8ff0')),
                ('target_db', models.CharField(choices=[(1, 'zine'), (2, 'chembl')], max_length=10, verbose_name='\u9776\u70b9\u6570\u636e\u5e93')),
                ('mol_file', models.FileField(upload_to='media/%Y/%m/%d/', verbose_name='\u9776\u70b9\u6587\u4ef6')),
                ('top_n', models.IntegerField(verbose_name='\u8fd4\u56de\u7ed3\u679c\u6570\u76ee')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u7528\u6237')),
            ],
            options={
                'verbose_name': '\u53cd\u5411\u865a\u62df\u7b5b\u9009',
                'verbose_name_plural': '\u53cd\u5411\u865a\u62df\u7b5b\u9009',
            },
        ),
        migrations.CreateModel(
            name='VirtualScreen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_name', models.CharField(max_length=20, verbose_name='\u4efb\u52a1\u540d\u79f0')),
                ('work_decs', models.CharField(default='', max_length=100, verbose_name='\u4efb\u52a1\u63cf\u8ff0')),
                ('mol_db', models.CharField(choices=[(1, 'zinc'), (2, 'chembl')], max_length=10, verbose_name='\u6570\u636e\u5e93\u9009\u62e9')),
                ('size_x', models.FloatField(verbose_name='size_x')),
                ('size_y', models.FloatField(verbose_name='size_y')),
                ('size_z', models.FloatField(verbose_name='size_y')),
                ('center_x', models.FloatField(verbose_name='center_x')),
                ('center_y', models.FloatField(verbose_name='center_y')),
                ('center_z', models.FloatField(verbose_name='center_z')),
                ('pdb_file', models.FileField(upload_to='media/%Y/%m/%d/', verbose_name='pdb\u6587\u4ef6')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u7528\u6237')),
            ],
            options={
                'verbose_name': '\u865a\u62df\u7b5b\u9009',
                'verbose_name_plural': '\u865a\u62df\u7b5b\u9009',
            },
        ),
        migrations.CreateModel(
            name='VsBlast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_name', models.CharField(max_length=20, verbose_name='\u4efb\u52a1\u540d\u79f0')),
                ('work_decs', models.CharField(default='', max_length=100, verbose_name='\u4efb\u52a1\u63cf\u8ff0')),
                ('sequence', models.CharField(max_length=1000, verbose_name='\u86cb\u767d\u5e8f\u5217')),
                ('protein_db', models.CharField(choices=[(1, 'zinc'), (2, 'chembl')], max_length=10)),
                ('e_value', models.CharField(choices=[(1, 1e-05), (2, 0.0001), (3, 0.001), (4, 0.01), (5, 0.01), (6, 1), (7, 10)], max_length=10, verbose_name='E\u503c\u9009\u62e9')),
                ('out_format', models.CharField(choices=[(1, 'pariwise'), (2, 'XML blast output'), (3, 'tabular')], max_length=10, verbose_name='\u8f93\u51fa\u683c\u5f0f\u9009\u62e9')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u7528\u6237')),
            ],
            options={
                'verbose_name': 'VsleadBlast',
                'verbose_name_plural': 'VsleadBlast',
            },
        ),
    ]
