# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-07 11:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autoduck',
            name='pdb_file',
            field=models.FileField(upload_to='media/autoduck/', verbose_name='pdb\u6587\u4ef6'),
        ),
    ]
