# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-25 11:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0003_auto_20180911_2042'),
    ]

    operations = [
        migrations.AddField(
            model_name='autoduck',
            name='username',
            field=models.CharField(default='a', max_length=20, verbose_name='\u7528\u6237\u540d'),
            preserve_default=False,
        ),
    ]
