# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-26 14:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0005_auto_20180926_1405'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admet',
            old_name='name',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='dynamic',
            old_name='name',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='reversevirtualscreen',
            old_name='name',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='virtualscreen',
            old_name='name',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='vsblast',
            old_name='name',
            new_name='user',
        ),
        migrations.AddField(
            model_name='admet',
            name='username',
            field=models.CharField(default='a', max_length=20, verbose_name='\u7528\u6237\u540d'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dynamic',
            name='username',
            field=models.CharField(default='a', max_length=20, verbose_name='\u7528\u6237\u540d'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reversevirtualscreen',
            name='username',
            field=models.CharField(default='a', max_length=20, verbose_name='\u7528\u6237\u540d'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='virtualscreen',
            name='username',
            field=models.CharField(default='a', max_length=20, verbose_name='\u7528\u6237\u540d'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vsblast',
            name='username',
            field=models.CharField(default='a', max_length=20, verbose_name='\u7528\u6237\u540d'),
            preserve_default=False,
        ),
    ]
