# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-28 15:34
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import works.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('works', '0007_autoduck2'),
    ]

    operations = [
        migrations.CreateModel(
            name='VirtualScreen2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, verbose_name='\u7528\u6237\u540d')),
                ('work_name', models.CharField(max_length=20, verbose_name='\u4efb\u52a1\u540d\u79f0')),
                ('work_decs', models.CharField(default='', max_length=100, verbose_name='\u4efb\u52a1\u63cf\u8ff0')),
                ('mol_db', models.CharField(choices=[(1, 'zinc'), (2, 'chembl')], max_length=10, verbose_name='\u6570\u636e\u5e93\u9009\u62e9')),
                ('lig_file', models.FileField(upload_to=works.models.upload_to, verbose_name='\u6b8b\u57fa\u6587\u4ef6')),
                ('pdb_file', models.FileField(upload_to=works.models.upload_to, verbose_name='pdb\u6587\u4ef6')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u7528\u6237')),
            ],
            options={
                'verbose_name': '\u865a\u62df\u7b5b\u90092',
                'verbose_name_plural': '\u865a\u62df\u7b5b\u90092',
            },
        ),
        migrations.AlterField(
            model_name='admet',
            name='mol_file',
            field=models.FileField(upload_to=works.models.upload_to, verbose_name='\u5c0f\u5206\u5b50\u6587\u4ef6'),
        ),
        migrations.AlterField(
            model_name='dynamic',
            name='frcmod_file',
            field=models.FileField(default='', upload_to=works.models.upload_to, verbose_name='frcmod\u6587\u4ef6'),
        ),
        migrations.AlterField(
            model_name='dynamic',
            name='lig_file',
            field=models.FileField(default='', upload_to=works.models.upload_to, verbose_name='lig\u6587\u4ef6'),
        ),
        migrations.AlterField(
            model_name='dynamic',
            name='mol_file',
            field=models.FileField(upload_to=works.models.upload_to, verbose_name='\u5c0f\u5206\u5b50\u6587\u4ef6'),
        ),
        migrations.AlterField(
            model_name='dynamic',
            name='protein_file',
            field=models.FileField(upload_to=works.models.upload_to, verbose_name='\u86cb\u767d\u6587\u4ef6'),
        ),
        migrations.AlterField(
            model_name='dynamic',
            name='s_file',
            field=models.FileField(default='', upload_to=works.models.upload_to, verbose_name='S\u4fe1\u606f\u6587\u4ef6'),
        ),
        migrations.AlterField(
            model_name='reversevirtualscreen',
            name='mol_file',
            field=models.FileField(upload_to=works.models.upload_to, verbose_name='\u9776\u70b9\u6587\u4ef6'),
        ),
        migrations.AlterField(
            model_name='virtualscreen',
            name='pdb_file',
            field=models.FileField(upload_to=works.models.upload_to, verbose_name='pdb\u6587\u4ef6'),
        ),
    ]
