# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-18 15:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0009_auto_20180928_1655'),
    ]

    operations = [
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.CharField(max_length=20, verbose_name='\u9776\u70b9\u540d\u79f0')),
            ],
            options={
                'verbose_name': '\u9776\u70b9\u540d\u79f0',
                'verbose_name_plural': '\u9776\u70b9\u540d\u79f0',
            },
        ),
    ]
