# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-27 19:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0010_target'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autoduck',
            name='mol_db',
            field=models.CharField(choices=[(1, 'zinc'), (2, 'chembl'), (3, 'wi')], max_length=10, verbose_name='\u6570\u636e\u5e93\u9009\u62e9'),
        ),
        migrations.AlterField(
            model_name='autoduck2',
            name='mol_db',
            field=models.CharField(choices=[(1, 'zinc'), (2, 'chembl'), (3, 'wi')], max_length=10, verbose_name='\u6570\u636e\u5e93\u9009\u62e9'),
        ),
        migrations.AlterField(
            model_name='virtualscreen',
            name='mol_db',
            field=models.CharField(choices=[(1, 'zinc'), (2, 'chembl'), (3, 'wi')], max_length=10, verbose_name='\u6570\u636e\u5e93\u9009\u62e9'),
        ),
        migrations.AlterField(
            model_name='virtualscreen2',
            name='mol_db',
            field=models.CharField(choices=[(1, 'zinc'), (2, 'chembl'), (3, 'wi')], max_length=10, verbose_name='\u6570\u636e\u5e93\u9009\u62e9'),
        ),
    ]
