# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-16 19:35
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import works.models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0011_auto_20181027_1917'),
    ]

    operations = [
        migrations.AddField(
            model_name='autoduck',
            name='price',
            field=models.IntegerField(default=10000, verbose_name='price'),
        ),
        migrations.AddField(
            model_name='autoduck2',
            name='price',
            field=models.IntegerField(default=10000, verbose_name='price'),
        ),
        migrations.AddField(
            model_name='virtualscreen',
            name='price',
            field=models.IntegerField(default=10000, verbose_name='price'),
        ),
        migrations.AddField(
            model_name='virtualscreen2',
            name='price',
            field=models.IntegerField(default=10000, verbose_name='price'),
        ),
        migrations.AlterField(
            model_name='autoduck',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='add_time'),
        ),
        migrations.AlterField(
            model_name='autoduck',
            name='mol_db',
            field=models.CharField(choices=[(1, 'zinc'), (2, 'chembl'), (3, 'wi')], max_length=10, verbose_name='mol_db'),
        ),
        migrations.AlterField(
            model_name='autoduck',
            name='pdb_file',
            field=models.FileField(upload_to=works.models.upload_to, verbose_name='pdb_file'),
        ),
        migrations.AlterField(
            model_name='autoduck',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AlterField(
            model_name='autoduck',
            name='work_decs',
            field=models.CharField(default='', max_length=100, verbose_name='work_decs'),
        ),
        migrations.AlterField(
            model_name='autoduck',
            name='work_name',
            field=models.CharField(max_length=20, verbose_name='work_name'),
        ),
        migrations.AlterField(
            model_name='autoduck2',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='add_time'),
        ),
        migrations.AlterField(
            model_name='autoduck2',
            name='lig_file',
            field=models.FileField(upload_to=works.models.upload_to, verbose_name='lig_file'),
        ),
        migrations.AlterField(
            model_name='autoduck2',
            name='mol_db',
            field=models.CharField(choices=[(1, 'zinc'), (2, 'chembl'), (3, 'wi')], max_length=10, verbose_name='mol_db'),
        ),
        migrations.AlterField(
            model_name='autoduck2',
            name='pdb_file',
            field=models.FileField(upload_to=works.models.upload_to, verbose_name='pdb_file'),
        ),
        migrations.AlterField(
            model_name='autoduck2',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AlterField(
            model_name='autoduck2',
            name='work_decs',
            field=models.CharField(default='', max_length=100, verbose_name='work_decs'),
        ),
        migrations.AlterField(
            model_name='autoduck2',
            name='work_name',
            field=models.CharField(max_length=20, verbose_name='work_name'),
        ),
        migrations.AlterField(
            model_name='virtualscreen',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='add_time'),
        ),
        migrations.AlterField(
            model_name='virtualscreen',
            name='mol_db',
            field=models.CharField(choices=[(1, 'zinc'), (2, 'chembl'), (3, 'wi')], max_length=10, verbose_name='mol_db'),
        ),
        migrations.AlterField(
            model_name='virtualscreen',
            name='pdb_file',
            field=models.FileField(upload_to=works.models.upload_to, verbose_name='pdb_file'),
        ),
        migrations.AlterField(
            model_name='virtualscreen',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AlterField(
            model_name='virtualscreen',
            name='work_decs',
            field=models.CharField(default='', max_length=100, verbose_name='work_decs'),
        ),
        migrations.AlterField(
            model_name='virtualscreen',
            name='work_name',
            field=models.CharField(max_length=20, verbose_name='work_name'),
        ),
        migrations.AlterField(
            model_name='virtualscreen2',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='add_time'),
        ),
        migrations.AlterField(
            model_name='virtualscreen2',
            name='lig_file',
            field=models.FileField(upload_to=works.models.upload_to, verbose_name='lig_file'),
        ),
        migrations.AlterField(
            model_name='virtualscreen2',
            name='mol_db',
            field=models.CharField(choices=[(1, 'zinc'), (2, 'chembl'), (3, 'wi')], max_length=10, verbose_name='mol_db'),
        ),
        migrations.AlterField(
            model_name='virtualscreen2',
            name='pdb_file',
            field=models.FileField(upload_to=works.models.upload_to, verbose_name='pdb_file'),
        ),
        migrations.AlterField(
            model_name='virtualscreen2',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AlterField(
            model_name='virtualscreen2',
            name='work_decs',
            field=models.CharField(default='', max_length=100, verbose_name='work_decs'),
        ),
        migrations.AlterField(
            model_name='virtualscreen2',
            name='work_name',
            field=models.CharField(max_length=20, verbose_name='work_name'),
        ),
    ]
