# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-19 19:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0012_auto_20181116_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autoduck',
            name='pdb_file',
            field=models.FileField(upload_to='media', verbose_name='pdb_file'),
        ),
        migrations.AlterField(
            model_name='autoduck2',
            name='lig_file',
            field=models.FileField(upload_to='media', verbose_name='lig_file'),
        ),
        migrations.AlterField(
            model_name='autoduck2',
            name='pdb_file',
            field=models.FileField(upload_to='media', verbose_name='pdb_file'),
        ),
        migrations.AlterField(
            model_name='virtualscreen',
            name='pdb_file',
            field=models.FileField(upload_to='media', verbose_name='pdb_file'),
        ),
        migrations.AlterField(
            model_name='virtualscreen2',
            name='lig_file',
            field=models.FileField(upload_to='media', verbose_name='lig_file'),
        ),
        migrations.AlterField(
            model_name='virtualscreen2',
            name='pdb_file',
            field=models.FileField(upload_to='media', verbose_name='pdb_file'),
        ),
    ]
