# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-26 14:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0013_auto_20181119_1944'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autoduck',
            name='mol_db',
        ),
        migrations.AddField(
            model_name='autoduck',
            name='lig_file',
            field=models.FileField(default='a', upload_to='media', verbose_name='lig_file'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='autoduck',
            name='status',
            field=models.CharField(default='\u6392\u961f\u4e2d', max_length=10, verbose_name='status'),
        ),
    ]
