# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-29 20:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import works.models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0015_auto_20181126_1440'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autoduck2',
            name='mol_db',
        ),
        migrations.AddField(
            model_name='autoduck2',
            name='resi_file',
            field=models.FileField(default='a', upload_to=works.models.upload_to, verbose_name='lig_file'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='virtualscreen',
            name='user_db',
            field=models.FileField(null=True, upload_to=works.models.upload_to, verbose_name='user_db'),
        ),
        migrations.AddField(
            model_name='virtualscreen2',
            name='user_db',
            field=models.FileField(null=True, upload_to=works.models.upload_to, verbose_name='user_db'),
        ),
        migrations.AlterField(
            model_name='autoduck',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='autoduck',
            name='lig_file',
            field=models.FileField(upload_to=works.models.upload_to, verbose_name='lig_file'),
        ),
        migrations.AlterField(
            model_name='autoduck',
            name='pdb_file',
            field=models.FileField(upload_to=works.models.upload_to, verbose_name='pdb_file'),
        ),
        migrations.AlterField(
            model_name='autoduck',
            name='work_name',
            field=models.CharField(max_length=20, unique=True, verbose_name='work_name'),
        ),
        migrations.AlterField(
            model_name='autoduck2',
            name='lig_file',
            field=models.FileField(upload_to=works.models.upload_to, verbose_name='lig_file'),
        ),
        migrations.AlterField(
            model_name='autoduck2',
            name='pdb_file',
            field=models.FileField(upload_to=works.models.upload_to, verbose_name='pdb_file'),
        ),
        migrations.AlterField(
            model_name='autoduck2',
            name='work_name',
            field=models.CharField(max_length=20, unique=True, verbose_name='work_name'),
        ),
        migrations.AlterField(
            model_name='virtualscreen',
            name='mol_db',
            field=models.CharField(choices=[(1, 'zinc'), (2, 'chembl'), (3, 'wi')], max_length=10, null=True, verbose_name='mol_db'),
        ),
        migrations.AlterField(
            model_name='virtualscreen',
            name='pdb_file',
            field=models.FileField(upload_to=works.models.upload_to, verbose_name='pdb_file'),
        ),
        migrations.AlterField(
            model_name='virtualscreen',
            name='work_name',
            field=models.CharField(max_length=20, unique=True, verbose_name='work_name'),
        ),
        migrations.AlterField(
            model_name='virtualscreen2',
            name='mol_db',
            field=models.CharField(choices=[(1, 'zinc'), (2, 'chembl'), (3, 'wi')], max_length=10, null=True, verbose_name='mol_db'),
        ),
        migrations.AlterField(
            model_name='virtualscreen2',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True, verbose_name='user'),
        ),
    ]
