# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-30 09:09
from __future__ import unicode_literals

from django.db import migrations, models
import works.models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0016_auto_20181129_2059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='virtualscreen2',
            name='lig_file',
        ),
        migrations.AddField(
            model_name='virtualscreen2',
            name='resi_file',
            field=models.FileField(default='a', upload_to=works.models.upload_to, verbose_name='resi_file'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='autoduck2',
            name='resi_file',
            field=models.FileField(upload_to=works.models.upload_to, verbose_name='resi_file'),
        ),
        migrations.AlterField(
            model_name='virtualscreen2',
            name='pdb_file',
            field=models.FileField(upload_to=works.models.upload_to, verbose_name='pdb_file'),
        ),
        migrations.AlterField(
            model_name='virtualscreen2',
            name='work_name',
            field=models.CharField(max_length=20, unique=True, verbose_name='work_name'),
        ),
    ]
