# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-04 12:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0019_auto_20181204_0941'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AutoDuck',
            new_name='AutoDock',
        ),
        migrations.RenameModel(
            old_name='AutoDuck2',
            new_name='AutoDock2',
        ),
    ]
