# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-06 11:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0020_auto_20181204_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='autodock',
            name='out_path',
            field=models.CharField(default='', max_length=100, verbose_name='out_path'),
        ),
        migrations.AddField(
            model_name='autodock2',
            name='out_path',
            field=models.CharField(default='', max_length=100, verbose_name='out_path'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(upload_to='banner/', verbose_name='\u8f6e\u64ad\u56fe\u7247'),
        ),
    ]
