# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-06 16:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0021_auto_20181206_1116'),
    ]

    operations = [
        migrations.AddField(
            model_name='autodock',
            name='affinity',
            field=models.CharField(default='\u4e2d\u5fc3\u4f4d\u7f6e\u4e0d\u5408\u7406\u65e0\u6cd5\u5bf9\u63a5', max_length=100, verbose_name='affinity'),
        ),
        migrations.AddField(
            model_name='autodock2',
            name='affinity',
            field=models.CharField(default='\u4e2d\u5fc3\u4f4d\u7f6e\u4e0d\u5408\u7406\u65e0\u6cd5\u5bf9\u63a5', max_length=100, verbose_name='affinity'),
        ),
        migrations.AlterField(
            model_name='autodock',
            name='out_path',
            field=models.FileField(null=True, upload_to=b'', verbose_name='out_path'),
        ),
        migrations.AlterField(
            model_name='autodock2',
            name='out_path',
            field=models.FileField(null=True, upload_to=b'', verbose_name='out_path'),
        ),
    ]
