# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-07 15:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0024_auto_20181207_1539'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='screen2',
            options={'verbose_name': '\u865a\u62df\u7b5b\u90092\u7ed3\u679c', 'verbose_name_plural': '\u865a\u62df\u7b5b\u90092\u7ed3\u679c'},
        ),
    ]
