# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-07 20:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0025_auto_20181207_1547'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='screen',
            name='user',
        ),
        migrations.RemoveField(
            model_name='screen2',
            name='user',
        ),
    ]
