# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-08 19:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0026_auto_20181207_2024'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Screen2',
        ),
        migrations.AddField(
            model_name='screen',
            name='screen_cat',
            field=models.CharField(default='a', max_length=10, verbose_name='\u7b5b\u9009\u7c7b\u522b'),
            preserve_default=False,
        ),
    ]
