# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-28 18:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0027_auto_20181208_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autodock',
            name='affinity',
            field=models.CharField(default='the position is unreasonable', max_length=100, verbose_name='affinity'),
        ),
        migrations.AlterField(
            model_name='autodock',
            name='status',
            field=models.CharField(default='waiting', max_length=10, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='autodock2',
            name='affinity',
            field=models.CharField(default='the position is unreasonable', max_length=100, verbose_name='affinity'),
        ),
        migrations.AlterField(
            model_name='autodock2',
            name='status',
            field=models.CharField(default='waiting', max_length=10, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='virtualscreen',
            name='mol_db',
            field=models.CharField(choices=[('zine', 'zinc'), ('chembl', 'chembl'), ('wi', 'wi')], max_length=10, null=True, verbose_name='mol_db'),
        ),
        migrations.AlterField(
            model_name='virtualscreen',
            name='status',
            field=models.CharField(default='waiting', max_length=10, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='virtualscreen2',
            name='status',
            field=models.CharField(default='waiting', max_length=10, verbose_name='status'),
        ),
    ]
