# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-03-07 20:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0029_auto_20190118_1830'),
    ]

    operations = [
        migrations.AddField(
            model_name='virtualscreen',
            name='target',
            field=models.CharField(default='', max_length=100000, verbose_name='target'),
        ),
        migrations.AddField(
            model_name='virtualscreen2',
            name='target',
            field=models.CharField(default='', max_length=100000, verbose_name='target'),
        ),
    ]
