# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-05-30 11:25
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import works.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('works', '0030_auto_20190307_2009'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_name', models.CharField(max_length=20, unique=True, verbose_name='work_name')),
                ('algorithm', models.CharField(choices=[('AutoDock', 'AutoDock'), ('AutoDock-vina', 'AutoDock-vina'), ('Glide', 'Glide')], max_length=20)),
                ('size_x', models.FloatField(null=True, verbose_name='size_x')),
                ('size_y', models.FloatField(null=True, verbose_name='size_y')),
                ('size_z', models.FloatField(null=True, verbose_name='size_z')),
                ('center_x', models.FloatField(null=True, verbose_name='center_x')),
                ('center_y', models.FloatField(null=True, verbose_name='center_y')),
                ('center_z', models.FloatField(null=True, verbose_name='center_z')),
                ('resn', models.CharField(max_length=100, null=True, verbose_name='resn')),
                ('pdb_file', models.FileField(upload_to=works.models.dock_upload_to, verbose_name='pdb_file')),
                ('lig_file', models.FileField(upload_to=works.models.dock_upload_to, verbose_name='lig_file')),
                ('reference_file', models.FileField(default='', upload_to=works.models.dock_upload_to, verbose_name='reference_file')),
                ('status', models.CharField(default='waiting', max_length=10, verbose_name='status')),
                ('out_path', models.FileField(null=True, upload_to=b'', verbose_name='out_path')),
                ('affinity', models.CharField(default='the position is unreasonable', max_length=100, verbose_name='affinity')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='add_time')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': '\u5206\u5b50\u5bf9\u63a5',
                'verbose_name_plural': '\u5206\u5b50\u5bf9\u63a5',
            },
        ),
    ]
