# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-05-30 15:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0032_auto_20190530_1211'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeaTarget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_name', models.CharField(max_length=100, verbose_name='work_name')),
                ('smiles', models.CharField(max_length=200, verbose_name='smiles')),
                ('target', models.CharField(default='null', max_length=500, verbose_name='targets')),
            ],
        ),
        migrations.CreateModel(
            name='SeaVirScreen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_name', models.CharField(max_length=100, verbose_name='work_name')),
                ('affinity', models.FloatField(verbose_name='affinity')),
                ('path', models.FileField(upload_to=b'', verbose_name='out_file')),
            ],
            options={
                'verbose_name': '\u865a\u62df\u7b5b\u9009\u7ed3\u679c',
                'verbose_name_plural': '\u865a\u62df\u7b5b\u9009\u7ed3\u679c',
            },
        ),
        migrations.RemoveField(
            model_name='virscreen',
            name='lig_file',
        ),
        migrations.AddField(
            model_name='virscreen',
            name='resn',
            field=models.FileField(null=True, upload_to=b'', verbose_name='resn'),
        ),
    ]
