# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-05-30 18:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import works.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('works', '0033_auto_20190530_1517'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gbsa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_name', models.CharField(max_length=100, verbose_name='work_name')),
                ('pdb_file', models.FileField(upload_to=works.models.gbsa_upload_to, verbose_name='pdb_file')),
                ('lig_file', models.FileField(upload_to=works.models.gbsa_upload_to, verbose_name='pdb_file')),
                ('complex_file', models.FileField(upload_to=works.models.gbsa_upload_to, verbose_name='pdb_file')),
                ('status', models.CharField(default='wating', max_length=20, verbose_name='status')),
                ('email', models.CharField(max_length=100, verbose_name='email')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'gbsa',
                'verbose_name_plural': 'gbsa',
            },
        ),
        migrations.AlterModelOptions(
            name='seatarget',
            options={'verbose_name': 'SEA\u9810\u6e2c\u7ed3\u679c', 'verbose_name_plural': 'SEA\u9810\u6e2c\u7ed3\u679c'},
        ),
    ]
