# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-05-30 20:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0034_auto_20190530_1826'),
    ]

    operations = [
        migrations.AddField(
            model_name='gbsa',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='add_time'),
        ),
        migrations.AlterField(
            model_name='gbsa',
            name='status',
            field=models.CharField(default='waiting', max_length=20, verbose_name='status'),
        ),
    ]
