# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-05-31 04:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0036_auto_20190531_0345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='virscreen',
            name='resn',
            field=models.CharField(max_length=100, null=True, verbose_name='resn'),
        ),
    ]
